source "https://rubygems.org"

gem 'tamagochi_gem', '>=0.2.0', git: 'https://github.com/Blekborn/RubyHW/tree/main/HW3/tamagochi_gem'

# Specify your gem's dependencies in tamagochi_gem.gemspec
gemspec
